version: "3.9"
services:
  db:
    image: postgres:16
    container_name: pg16
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: applocal
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 20
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports: ["5050:80"]
    depends_on: [db]
volumes:
  pgdata:
